### PR TITLE
rewrote functions using deprecated JQuery.once

### PR DESCRIPTION
**Pull request by kreynen-du**

### CODE REVIEW

**Comment by kreynen-du** [comment]
I'm still working on https://github.com/University-of-Denver/drupal-composer-managed/pull/1 this morning. I cleared up most of the js errors, but I don't know what has to be on a page to test that the functionality is actually working... a good indication that the js isn't being loaded at the right layer of the stack. 

There is still one related to `sessionStorage.scrollTop.clear is not a function`. I'll create a separate Wrike task to resolve that.

I updated https://ducloudwiki.atlassian.net/wiki/spaces/DS/pages/596836354/PL+Drupal+Theme with the steps to replace the copy Composer is adding to the project with a copy that can push commits back to GitHub.

**Review by CharlesJ3 — COMMENTED** [review]
Looks good to me, curious if you left the old code commented out on purpose? Is that going away when things are verified good to go? It did make comparing the functions easier on my end at least!

**Review by CharlesJ3 — APPROVED** [review]

**Comment by joshua-mcgehee** [comment]
@kreynen-du and @CharlesJ3, Can we merge this?

**Comment by kreynen-du** [comment]
We can as long as everyone understands that we're not testing anything beyond the lack of the error. Until this theme is used on a site that actually uses these functions, we're only smell testing the code. I'm also not trying to write any of this in a way that works for both D9/Symfony4/Twig2 and D10/Symfony6/Twig3. pl_drupal ^3.0.0-alpha2 is only going to work with ^D10.3.x
